### ISSUE TITLE
Question about little FPN in ViT-B

### ISSUE THREAD

**Issue by lh-zhu** [raoyongming/DenseCLIP#14]
Greetings, I like your great work and try to follow it to do something!

I noticed that your ViT-B-16 contains a little FPN, I wonder why you prefer to add this, and what will happen if we remove this?

**Comment by jiangyitong** [comment]
Hi, do you have any conclusions about this? Thanks a lot.

**Comment by jiangyitong** [comment]
> Greetings, I like your great work and try to follow it to do something!
> 
> I noticed that your ViT-B-16 contains a little FPN, I wonder why you prefer to add this, and what will happen if we remove this?
