### ISSUE TITLE
what is the value of gamma?

### ISSUE THREAD

**Issue by Richardych** [raoyongming/DenseCLIP#16]
Hi, I found the value of self.gamma is different between your paper (gamma==1e-3) and your code (gamma==1e-4), which one should I use to reproduce your results? Thanks.

**Comment by wl-zhao** [comment]
Sorry for the confusion. It was a typo in the v1 version of our paper on arxiv. We have updated the paper on arxiv. Gamma should be 1e-4, please refer to the [newest version](https://arxiv.org/abs/2112.01518).
