### ISSUE TITLE
the results of DenseCLIP on Cityscapes

### ISSUE THREAD

**Issue by Richardych** [raoyongming/DenseCLIP#22]
Hi,  

this is a great work. Have you tried DenseCLIP on other seg datasets? e.g., Cityscapes.

Because I tried with the code, but the result is not good enough.

thanks.

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. We didn't test our method on Cityscapes.  The training config is tuned on ADE20k in our experiments. I think it may need some effort to adapt the hyper-parameters on the new dataset.

**Comment by Richardych** [comment]
> 

thanks for your reply.

I only get 3.5% mIoU on Cityscapes val set with your code, can you have a try on Cityscaples?

**Comment by Richardych** [comment]
> Hi, thanks for your interest in our work. We didn't test our method on Cityscapes. The training config is tuned on ADE20k in our experiments. I think it may need some effort to adapt the hyper-parameters on the new dataset.

thanks for your reply. I will try it.
