### ISSUE TITLE
Question about ADE20K dataset

### ISSUE THREAD

**Issue by wenyuqing** [raoyongming/DenseCLIP#23]
Hi, I want to reproduce your experiment on ADE20K  but when I download the dataset I noticed that the ADE website had updated the dataset so the file structure and the number of training images is different from the older _ADEChallengeData2016_. I wonder which version do you use in your work?
The older version of ADE20k contains 20210 training images.
The newer version containes 25K training images as shown on their website.
![image](https://user-images.githubusercontent.com/48059861/180912531-3aaef410-d6a8-4831-929c-7cf475e90dfb.png)

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. We use the `ADEChallengeData2016` version in our experiments following previous work. I just check the folder in our server, there are 20,210/2,000 images in the train/val set.

**Comment by wenyuqing** [comment]
> Hi, thanks for your interest in our work. We use the `ADEChallengeData2016` version in our experiments following previous work. I just check the folder in our server, there are 20,210/2,000 images in the train/val set.

Thanks for your quick reply!
