### ISSUE TITLE
A stupid question about auxiliary loss for Object detection & instance segmentation. 

### ISSUE THREAD

**Issue by waxnkw** [raoyongming/DenseCLIP#26]
The paper said, "we do not have ground truth segmentation label.". I can understand there is no segmentation mask for detection, but why is there no segmentation mask for instance segmentation task?

**Comment by raoyongming** [comment]
Hi @waxnkw, thanks for your interest in our work. Here we want to say we don't have ground truth segmentation labels **like semantic segmentation**.  For COCO, we cannot assign labels to the background regions if we only use the instance segmentation labels.

**Comment by waxnkw** [comment]
Thanks, so is the BCE loss applied to distinguish foreground objects and background?

**Comment by raoyongming** [comment]
We generate the segmentation mask using the bounding boxes or instance mask labels. We assign the corresponding labels for the foreground objects and set the rest regions as the background.

**Comment by waxnkw** [comment]
Thanks!
