### ISSUE TITLE
Question about implementation of CLIPResNet

### ISSUE THREAD

**Issue by littlepenguin89106** [raoyongming/DenseCLIP#29]
Hi,
The modified ResNet in CLIP uses attention pooling, and the comments in CLIPResNet class are also noted that.
However, I didn't see any related operations in CLIPResNet.
I know there is another CLIPResNetWithAttention class, but according the configs, I think it is for DenseCLIP not CLIP?

**Comment by raoyongming** [comment]
Hi @littlepenguin89106, sorry for the confusion. The pretrained CLIP ResNet models are based on `CLIPResNetWithAttention` class. The `CLIPResNet` is the modified version that is only used in our early experiments to verify whether attention pooling is necessary.

**Comment by littlepenguin89106** [comment]
Ok, Thanks for your reply!
