### ISSUE TITLE
Additional Package Dependencies

### ISSUE THREAD

**Issue by ChenDelong1999** [raoyongming/DenseCLIP#3]
Nice work!
But when creating a new conda environment for DenseCLIP, I found the following packages are required:

```
regex
ftfy
```
After using pip to install these packages, the code works fine.

(Moreover, seems that it's not necessary to install `fvcore` explicitly.

**Comment by raoyongming** [comment]
Hi, thanks for pointing out this.

I have updated the `README.md`. The `fvcore` library is only used in `get_flops.py`, which is not necessary for training and evaluation.

**Comment by ChenDelong1999** [comment]
Thanks~
