### ISSUE TITLE
Is default training iterations enough to reach the paper performance?

### ISSUE THREAD

**Issue by williamlus** [raoyongming/DenseCLIP#30]
I try to train a DenseCLIP model based on CLIP ResNet-50 using the default configuration, where the number of iterations is 80,000. But I find that after training, the model has mIoU 39.46 in the testing set, which is smaller than 43.5 shown in the paper. The following images are the testing result and training history. 
![image](https://user-images.githubusercontent.com/67042315/197716924-4b585b6c-b789-47be-a804-01ee9ffac978.png)
![image](https://user-images.githubusercontent.com/67042315/197717025-e1edf654-130a-40e4-9de6-65fc68eebdc9.png)
![image](https://user-images.githubusercontent.com/67042315/197717033-f9cc7926-1ba0-43ff-bc7c-19f119f93297.png)

**Comment by raoyongming** [comment]
Hi @williamlus, thanks for your interest in our work. You can reproduce the results by running `bash dist_train.sh configs/denseclip_fpn_res50_512x512_80k.py 8`. We have already added necessary hyper-parameters in `denseclip_fpn_res50_512x512_80k.py`. It is worth noting that the global batch size should be set to 32 in this setting (i.e., 8 GPUs should be used). Maybe you can refer to https://github.com/raoyongming/DenseCLIP/issues/13.
