### ISSUE TITLE
About prompt text

### ISSUE THREAD

**Issue by good-demo** [raoyongming/DenseCLIP#31]
Thanks for your sharing work

I want to know how the prompt text create?(script or manual )

Can you provide some examples？

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. The prompt text is created using the name of semantic classes from the dataset. For example, in the segmentation task, we use the names provided in [mmseg](https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/mmseg/datasets/ade.py#L12) to create [the class embeddings](https://github.com/raoyongming/DenseCLIP/blob/3b72447dee3f622f3716738140161ef9f763c72f/segmentation/denseclip/denseclip.py#L83)

**Comment by good-demo** [comment]
Thanks for your reply

**Comment by anurag-198** [comment]
> Hi, thanks for your interest in our work. The prompt text is created using the name of semantic classes from the dataset. For example, in the segmentation task, we use the names provided in [mmseg](https://github.com/open-mmlab/mmsegmentation/blob/7b09967fcc5a8171fc375d9a7f1b40962e40f350/mmseg/datasets/ade.py#L12) to create [the class embeddings](https://github.com/raoyongming/DenseCLIP/blob/3b72447dee3f622f3716738140161ef9f763c72f/segmentation/denseclip/denseclip.py#L83)

Hi, Thanks for your work. In the paper, it is mentioned that you use CoOp to generate prompts where <p1, p2,...,pn> are learnable. But from the code it seems that only the class labels are used for generating the prompt text ? Can you please confirm this, if I am missing something ?
