### ISSUE TITLE
Prompt learning via CoOp

### ISSUE THREAD

**Issue by anurag-198** [raoyongming/DenseCLIP#34]
Hi, Thanks for your work. In the paper, it is mentioned that you use CoOp to generate prompts where <p1, p2,...,pn> are learnable. But from the code it seems that only the class labels are used for generating the prompt text ? Can you please confirm this, if I am missing something ?

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. The text prompt used in DenseCLIP consists of the labels prompts defined [here](https://github.com/raoyongming/DenseCLIP/blob/3b72447dee3f622f3716738140161ef9f763c72f/segmentation/denseclip/denseclip.py#L88) and class labels. They are combined and fed into the text encoder to generate the text features [here](https://github.com/raoyongming/DenseCLIP/blob/3b72447dee3f622f3716738140161ef9f763c72f/segmentation/denseclip/denseclip.py#L179).

**Comment by anurag-198** [comment]
Ahh, totally missed the the context prompt learnable parameter :) Thanks for making it simpler and quick response.
