### ISSUE TITLE
about single-scale and multi-scale settings

### ISSUE THREAD

**Issue by chenhao-zju** [raoyongming/DenseCLIP#38]
The default setting is multi-scale model, which is provided in the github. What about the single-scale model? Could you please provide the config files for it.

**Comment by raoyongming** [comment]
Hi @chenhao-zju, they share the same config file. You can simply add/remove the `--aug-test` flag to switch between the two modes ([here](https://github.com/raoyongming/DenseCLIP#training--evaluation-on-ade20k)).
