### ISSUE TITLE
question about eos_indx in model.py

### ISSUE THREAD

**Issue by qiulesun** [raoyongming/DenseCLIP#4]
Nice work!         For class of CLIPTextContextEncoder, why did the line [eos_indx = text.argmax(dim=-1) + N2](https://github.com/raoyongming/DenseCLIP/blob/master/segmentation/denseclip/models.py#L691) add N2 ?

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work.

As shown in Figure 3, the input of the text encoder is [`<bos>`, `p1`, ..., `pN`, `class name`, `<eos>`]. We can use `text.argmax(dim=-1)` to get the index of the `<eos>` in  [`<bos>`, `class name`, `<eos>`] following the implementation of CLIP. By adding N2, we can obtain the index of the `<eos>` after inserting the learnable context [`p1`, ..., `pN`].

**Comment by qiulesun** [comment]
Thanks for your quick reply.
In [line697](https://github.com/raoyongming/DenseCLIP/blob/master/segmentation/denseclip/models.py#L697), the input of the text encoder  is changed to [<bos>, class name1, p1, ..., pN, class name 120, <eos>] instead of [<bos>, p1, ..., pN, class name, <eos>]. So the way to get the index of the <eos> bothers me.

**Comment by raoyongming** [comment]
`x_text` actually is [`<bos>`, `class name`, `<eos>`]. Therefore, in line 697, `x_text[:,:,0:1]` is the `<bos>` and  `x_text[:, :, 1:]` is [`class name`, `<eos>`].

**Comment by qiulesun** [comment]
I understand it. Thanks for your explanation again.

**Comment by raoyongming** [comment]
The idea of learnable context is from [CoOp](https://arxiv.org/abs/2109.01134). Their results (figure 3) show different ways to insert the learnable context may not largely affect the final performance. Therefore, we directly use their default setting in our framework.

**Comment by qiulesun** [comment]
Do your consider releasing mIoU values of other mainstream segmentation datatsets, i.e., Pascal Context and Cityscapes or providing corresponding cofig scripts to fineturn DenseCLIP ?

**Comment by raoyongming** [comment]
As ADE20k is more challenging on other datasets, we conducted our main experiments on this dataset. We may test our method on more datasets in the future. Since our implementation is based on `mmseg`,  I think it is quite easy to extend our implementation to other datasets by changing the datasets and the number of classes in config files.

**Comment by qiulesun** [comment]
@raoyongming 
Based on mmseg, DenseCLIP can be easily applied to other segmentation datasets. However, for hyperparameters,  baselr, lr of backbone, text_encoder, context_decoder, neck and head have to carefully be turned to get desired performance in terms of different datasets.

**Comment by raoyongming** [comment]
I agree.  Since I am busy on other projects currently, I may try it in the future. Please tell us if you have any results.

**Comment by qiulesun** [comment]
@raoyongming 
Can you give me some advice about setting hyperparameters, e.g.,[ baselr, lr of backbone, text_encoder, context_decoder, neck and head](https://github.com/raoyongming/DenseCLIP/blob/master/segmentation/configs/denseclip_fpn_res50_512x512_80k.py#L53) ?

**Comment by raoyongming** [comment]
[`mmseg`](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/sem_fpn) use the same `lr` config for ADE and Cityscapes. I think you can start by using the same configurations on these new datasets.
