### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by kexibudongshi** [raoyongming/DenseCLIP#42]
I am very interested in reading the paper, but the pre-model prompting mentioned in the paper seems to be missing in the code, could you add this part of the code? I am very interested in this part。

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. Please refer to https://github.com/raoyongming/DenseCLIP/issues/11

**Comment by kexibudongshi** [comment]
unsubscribe.Only post-model prompting,no pre-model prompting




汪福辰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "raoyongming/DenseCLIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月11日(星期二) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [raoyongming/DenseCLIP] Code (Issue #42)





 
Hi, thanks for your interest in our work. Please refer to #11
