### ISSUE TITLE
Question about training process

### ISSUE THREAD

**Issue by 0xac9527** [raoyongming/DenseCLIP#48]
I run following for training on ade dataset, 

   bash dist_train.sh configs/denseclip_fpn_res50_512x512_80k.py 8

command lines output as follows,  but training process goes on....

  [] [] are misaligned params in CLIPResNet
  [] [] are misaligned params in text encoder

It seems language-image align failed, how can I fix this problem?

**Comment by needsee** [comment]
It means successful loading

**Comment by raoyongming** [comment]
> It means successful loading

Yes. These two messages mean the misaligned parameters are empty lists. It is just used to check whether the pre-trained model is successfully loaded.
