### ISSUE TITLE
How did you freeze the text encoder in the code?

### ISSUE THREAD

**Issue by wujiang0156** [raoyongming/DenseCLIP#56]
Great work! However, I have some questions.
**4.3. DenseCLIP for Any Visual Backbone**
![image](https://github.com/user-attachments/assets/48e1aaad-59e2-43f1-a893-c9c12d6dbc2c)

How did you freeze the text encoder in the code?

**Comment by raoyongming** [comment]
See https://github.com/raoyongming/DenseCLIP/issues/33

**Comment by wujiang0156** [comment]
> See #33

Thank you so much
